"preserve_hierarchy": true

"files": [
  {
    "source": "/src/**/*.md",
    "translation": "/translations/%two_letters_code%/src/**/%original_file_name%"
  },
  {
    "source": "glossary.yaml",
    "translation": "/translations/%two_letters_code%/%original_file_name%"
  }
]
