"preserve_hierarchy": true
"base_path": "content"
"files": [
  {
    "source": "/**/*.*",
    "translation": "/translations/%locale%/**/%original_file_name%",
    "ignore" : [
      "localization.pot"
    ]  
  },
  {
    "source": "localization.pot",
    "translation": "/translations/%locale%/%file_name%.po"
  }
]
